version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=your_password
      - MYSQL_DATABASE=your_database
    command: dockerize -wait tcp://mysql:3306 -timeout 60m npm start
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
