FROM node:latest

RUN apt-get update && \
    apt-get install -y wget && \
    wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz && \
    tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz && \
    rm dockerize-linux-amd64-v0.6.1.tar.gz

WORKDIR /usr/src/app

COPY app/ ./

RUN npm install

EXPOSE 3000

CMD ["dockerize", "-wait", "tcp://mysql:3306", "-timeout", "60m", "npm", "start"]
